/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so19093033" "THE IDOLM@STER webラジオ～一番くじ&クレーンキングスペシャル～きゅぴぴぴーん★うがー!!（第1回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so19306829" "THE IDOLM@STER webラジオ～一番くじ&クレーンキングスペシャル～きゅぴぴぴーん★うがー!!（第2回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so19848503" "THE IDOLM@STER webラジオ～一番くじ&クレーンキングスペシャル～きゅぴぴぴーん★うがー!!（第3回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so20015214" "THE IDOLM@STER webラジオ～一番くじ&クレーンキングスペシャル～きゅぴぴぴーん★うがー!!（第4回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so20267214" "THE IDOLM@STER webラジオ～一番くじ&クレーンキングスペシャル～きゅぴぴぴーん★うがー!!（第5回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so21137283" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第1回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so21280628" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第2回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so21466807" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第3回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so21750824" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第4回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so21991215" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第5回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so22155331" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第6回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so22352076" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第7回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so22542775" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第8回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so22775934" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第9回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so23061161" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜皆さん、高槻やよいの部屋へようこそ！（第10回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so23458748" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第1回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so23691459" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第2回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so23899272" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第3回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so24158720" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第4回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so24339685" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第5回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so24598930" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第6回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so24808412" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第7回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so25008953" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第8回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so25208119" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第9回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so25533725" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第10回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so25673404" "THE IDOLM@STER webラジオ〜一番くじ＆クレーンキングスペシャル〜響チャレンジ！-プロデューサー！全員集合だぞ！！-（第11回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so26200729" "アイドルマスターwebラジオ～クレーンキング&一番くじスペシャル～つかんでひいてぱんぱかぱーん！わたしたちも盛り上げM@S！（第2回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so26441735" "アイドルマスターwebラジオ～クレーンキング&一番くじスペシャル～つかんでひいてぱんぱかぱーん！わたしたちも盛り上げM@S！（第3回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so26623974" "アイドルマスターwebラジオ～クレーンキング&一番くじスペシャル～つかんでひいてぱんぱかぱーん！わたしたちも盛り上げM@S！（第4回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so26854543" "アイドルマスターwebラジオ～クレーンキング&一番くじスペシャル～つかんでひいてぱんぱかぱーん！わたしたちも盛り上げM@S！（第5回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so27082846" "アイドルマスターwebラジオ～クレーンキング&一番くじスペシャル～つかんでひいてぱんぱかぱーん！わたしたちも盛り上げM@S！（第6回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so27272885" "アイドルマスターwebラジオ～クレーンキング&一番くじスペシャル～つかんでひいてぱんぱかぱーん！わたしたちも盛り上げM@S！（第7回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so27522860" "アイドルマスターwebラジオ～クレーンキング&一番くじスペシャル～つかんでひいてぱんぱかぱーん！わたしたちも盛り上げM@S！（第8回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so27744753" "アイドルマスターwebラジオ～クレーンキング&一番くじスペシャル～つかんでひいてぱんぱかぱーん！わたしたちも盛り上げM@S！（第9回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so28567851" "THE IDOLM@STER webラジオ～バンプレストスペシャル～ラジオは……遊びでは、ないですから（第1回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so28811147" "THE IDOLM@STER webラジオ～バンプレストスペシャル～ラジオは……遊びでは、ないですから（第2回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so28962133" "THE IDOLM@STER webラジオ～バンプレストスペシャル～ラジオは……遊びでは、ないですから（第3回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so29185344" "THE IDOLM@STER webラジオ～バンプレストスペシャル～ラジオは……遊びでは、ないですから（第4回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so29359627" "THE IDOLM@STER webラジオ～バンプレストスペシャル～ラジオは……遊びでは、ないですから（第5回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so29564440" "THE IDOLM@STER webラジオ～バンプレストスペシャル～ラジオは……遊びでは、ないですから（第6回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so29765333" "THE IDOLM@STER webラジオ～バンプレストスペシャル～やるときはやる、いつかは未定！（第7回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so29992128" "THE IDOLM@STER webラジオ～バンプレストスペシャル～やるときはやる、いつかは未定！（第8回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so30151626" "THE IDOLM@STER webラジオ～バンプレストスペシャル～やるときはやる、いつかは未定！（第9回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so30309696" "THE IDOLM@STER webラジオ～バンプレストスペシャル～やるときはやる、いつかは未定！（第10回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so30559392" "THE IDOLM@STER webラジオ～バンプレストスペシャル～やるときはやる、いつかは未定！（第11回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so30768548" "THE IDOLM@STER webラジオ～バンプレストスペシャル～やるときはやる、いつかは未定！（第12回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so30956922" "THE IDOLM@STER webラジオ～バンプレストスペシャル～にゃんにゃんラジオ、はじまるにゃ！（第1回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so31176506" "THE IDOLM@STER webラジオ～バンプレストスペシャル～にゃんにゃんラジオ、はじまるにゃ！（第2回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so31342834" "THE IDOLM@STER webラジオ～バンプレストスペシャル～にゃんにゃんラジオ、はじまるにゃ！（第3回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so31504852" "THE IDOLM@STER webラジオ～バンプレストスペシャル～にゃんにゃんラジオ、はじまるにゃ！（第4回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so31705622" "THE IDOLM@STER webラジオ～バンプレストスペシャル～にゃんにゃんラジオ、はじまるにゃ！（第5回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so31865129" "THE IDOLM@STER webラジオ～バンプレストスペシャル～にゃんにゃんラジオ、はじまるにゃ！（第6回）"
/data/share/movie/sh/nicodl.sh "http://www.nicovideo.jp/watch/so32031969" "THE IDOLM@STER webラジオ～バンプレストスペシャル～ウサミン星からう～どっかーん！（第7回）"
